In [1]:
from pprint import pprint
import random
import pandas as pd
import numpy as np

import MOO_functions

In [2]:
# Damage scenario selection
ds_sel = 'DS2'

df = pd.read_excel(
    "DS_with_full_description.xlsx",
    sheet_name= ds_sel
)

# Repair time discretization (hours)
repair_time_interval = 0.25  # 15 minutes

# Build the reparations dictionary
time_reparation = {}

for _, row in df.iterrows():

    repair_time = float(row["fix time (hours)"])

    # Round up to the nearest interval
    repair_time = np.ceil(repair_time / repair_time_interval) * repair_time_interval

    time_reparation[str(row["Pipe ID"])] = {
        "t_r": repair_time
    }

print(f"{len(time_reparation)} repairs loaded.")
#time_reparation

106 repairs loaded.

In [3]:
# load the wdn as INP file WITH the broken pipes
input_inp = 'BBM-EPS_'+ds_sel+'mcg.inp'

# Export the new INP file with the controls
output_inp="BBM-EPS_"+ds_sel+"_restoration.inp"

In [4]:
# Number of crews
n_crews = 3

# Pipe IDs from the reparations dictionary
pipe_ids = list(time_reparation.keys())

# Number of repairs
n_rep = len(pipe_ids)

In [5]:
indexes = [24,14,87,10,2,78,75,4,39,104,9,77,3,89,23,7,81,29,43,101,6,11,30,73,8,5,0,42,44,98,55,41,1,15,61,74,91,21,32,64,26,94,80,16,88,18,84,72,58,17,66,69,38,86,33,96,25,56,40,70,46,92,62,50,31,35,27,71,28,93,12,82,67,60,83,63,99,22,97,13,103,100,59,47,95,37,53,105,20,85,90,79,76,52,36,34,45,54,65,57,102,48,68,19,49,51]
print(len(indexes))

106

In [6]:
# # List of indexes randomly ordered corresponding to the pipe IDs to be repaired
# indexes = list(range(len(pipe_ids)))
# random.shuffle(indexes)
# print(indexes[:20])

In [7]:
# Import the travel time matrix from the Excel file
dmatrix_df = pd.read_parquet(
    "TravelTime_"+ds_sel+".parquet"
)

# Normalize IDs so the repair dictionary and matrix use the same keys
dmatrix_df.index = dmatrix_df.index.map(str)
dmatrix_df.columns = dmatrix_df.columns.map(str)

dmatrix_df.head()

,1951,3414,4988,5251,3404,6005,1252,2408,3094,3293,...,538,5488,5567,5677,5778,5959,6041,854,869,892
1951,0.25,0.25,0.25,0.75,0.25,0.75,0.50,0.25,0.25,0.25,...,0.25,0.75,0.75,0.75,0.75,0.75,0.75,0.50,0.50,0.50
3414,0.25,0.25,0.25,0.50,0.25,0.75,0.25,0.25,0.25,0.25,...,0.25,0.50,0.75,0.50,0.75,0.75,0.75,0.25,0.25,0.25
4988,0.25,0.25,0.25,0.50,0.25,0.75,0.25,0.25,0.25,0.25,...,0.25,0.75,0.75,0.50,0.75,0.75,0.75,0.25,0.25,0.25
5251,0.75,0.50,0.50,0.25,0.75,0.25,0.50,0.50,0.75,0.50,...,0.50,0.25,0.25,0.25,0.25,0.25,0.25,0.50,0.50,0.50
3404,0.25,0.25,0.25,0.75,0.25,0.75,0.25,0.25,0.25,0.25,...,0.25,0.75,0.75,0.75,0.75,0.75,0.75,0.25,0.25,0.25

In [8]:
schedule = MOO_functions.create_schedule(
    reparations=time_reparation, 
    dmatrix=dmatrix_df, 
    pipe_ids=pipe_ids, 
    indexes=indexes, 
    n_crews=n_crews
    )

schedule

     Order  Pipe  Crew  Travel  Repair   Start  Finish
0        1  2881     1    0.50    6.75    0.50    7.25
1        2  2508     2    0.50    3.50    0.50    4.00
2        3  4584     3    0.50    2.75    0.50    3.25
3        4  1186     3    0.50    4.50    3.75    8.25
4        5  4988     2    0.25    7.25    4.25   11.50
..     ...   ...   ...     ...     ...     ...     ...
101    101  6041     1    0.75    2.75  134.50  137.25
102    103  2430     2    0.50    2.75  135.50  138.25
103    105  5691     3    0.50    3.25  137.75  141.00
104    104  4132     1    0.75    3.50  138.00  141.50
105    106  5105     2    0.75    2.75  139.00  141.75

[106 rows x 7 columns]

In [9]:
new_controls = MOO_functions.generate_controls(schedule=schedule)

new_controls

['; Pipe 2881',
 'LINK 2881_A CLOSED AT TIME 0.50',
 'LINK 2881_B CLOSED AT TIME 0.50',
 'LINK 2881 OPEN AT TIME 7.25',
 '; Pipe 2508',
 'LINK 2508_A CLOSED AT TIME 0.50',
 'LINK 2508_B CLOSED AT TIME 0.50',
 'LINK 2508 OPEN AT TIME 4.00',
 '; Pipe 4584',
 'LINK 4584_A CLOSED AT TIME 0.50',
 'LINK 4584_B CLOSED AT TIME 0.50',
 'LINK 4584 OPEN AT TIME 3.25',
 '; Pipe 1186',
 'LINK 1186_A CLOSED AT TIME 3.75',
 'LINK 1186_B CLOSED AT TIME 3.75',
 'LINK 1186 OPEN AT TIME 8.25',
 '; Pipe 4988',
 'LINK 4988_A CLOSED AT TIME 4.25',
 'LINK 4988_B CLOSED AT TIME 4.25',
 'LINK 4988 OPEN AT TIME 11.50',
 '; Pipe 3216',
 'LINK 3216_A CLOSED AT TIME 7.50',
 'LINK 3216_B CLOSED AT TIME 7.50',
 'LINK 3216 OPEN AT TIME 10.25',
 '; Pipe 3120',
 'LINK 3120_A CLOSED AT TIME 8.50',
 'LINK 3120_B CLOSED AT TIME 8.50',
 'LINK 3120 OPEN AT TIME 11.25',
 '; Pipe 3404',
 'LINK 3404_A CLOSED AT TIME 10.50',
 'LINK 3404_B CLOSED AT TIME 10.50',
 'LINK 3404 OPEN AT TIME 16.25',
 '; Pipe 2113',
 'LINK 2113_A CLOSED AT TIME 11.50',
 'LINK 2113_B CLOSED AT TIME 11.50',
 'LINK 2113 OPEN AT TIME 14.75',
 '; Pipe 869',
 'LINK 869_A CLOSED AT TIME 11.75',
 'LINK 869_B CLOSED AT TIME 11.75',
 'LINK 869 OPEN AT TIME 14.50',
 '; Pipe 3293',
 'LINK 3293_A CLOSED AT TIME 14.75',
 'LINK 3293_B CLOSED AT TIME 14.75',
 'LINK 3293 OPEN AT TIME 20.50',
 '; Pipe 3184',
 'LINK 3184_A CLOSED AT TIME 15.00',
 'LINK 3184_B CLOSED AT TIME 15.00',
 'LINK 3184 OPEN AT TIME 17.75',
 '; Pipe 5251',
 'LINK 5251_A CLOSED AT TIME 17.00',
 'LINK 5251_B CLOSED AT TIME 17.00',
 'LINK 5251 OPEN AT TIME 24.25',
 '; Pipe 4721',
 'LINK 4721_A CLOSED AT TIME 18.25',
 'LINK 4721_B CLOSED AT TIME 18.25',
 'LINK 4721 OPEN AT TIME 21.00',
 '; Pipe 163',
 'LINK 163_A CLOSED AT TIME 20.75',
 'LINK 163_B CLOSED AT TIME 20.75',
 'LINK 163 OPEN AT TIME 27.50',
 '; Pipe 2408',
 'LINK 2408_A CLOSED AT TIME 21.50',
 'LINK 2408_B CLOSED AT TIME 21.50',
 'LINK 2408 OPEN AT TIME 27.25',
 '; Pipe 3959',
 'LINK 3959_A CLOSED AT TIME 24.75',
 'LINK 3959_B CLOSED AT TIME 24.75',
 'LINK 3959 OPEN AT TIME 27.50',
 '; Pipe 2001',
 'LINK 2001_A CLOSED AT TIME 27.50',
 'LINK 2001_B CLOSED AT TIME 27.50',
 'LINK 2001 OPEN AT TIME 31.75',
 '; Pipe 2726',
 'LINK 2726_A CLOSED AT TIME 27.75',
 'LINK 2726_B CLOSED AT TIME 27.75',
 'LINK 2726 OPEN AT TIME 31.00',
 '; Pipe 5959',
 'LINK 5959_A CLOSED AT TIME 28.00',
 'LINK 5959_B CLOSED AT TIME 28.00',
 'LINK 5959 OPEN AT TIME 30.75',
 '; Pipe 288',
 'LINK 288_A CLOSED AT TIME 31.25',
 'LINK 288_B CLOSED AT TIME 31.25',
 'LINK 288 OPEN AT TIME 35.75',
 '; Pipe 1252',
 'LINK 1252_A CLOSED AT TIME 31.50',
 'LINK 1252_B CLOSED AT TIME 31.50',
 'LINK 1252 OPEN AT TIME 37.25',
 '; Pipe 2910',
 'LINK 2910_A CLOSED AT TIME 32.00',
 'LINK 2910_B CLOSED AT TIME 32.00',
 'LINK 2910 OPEN AT TIME 36.25',
 '; Pipe 3041',
 'LINK 3041_A CLOSED AT TIME 36.00',
 'LINK 3041_B CLOSED AT TIME 36.00',
 'LINK 3041 OPEN AT TIME 38.75',
 '; Pipe 3094',
 'LINK 3094_A CLOSED AT TIME 36.50',
 'LINK 3094_B CLOSED AT TIME 36.50',
 'LINK 3094 OPEN AT TIME 42.25',
 '; Pipe 6005',
 'LINK 6005_A CLOSED AT TIME 38.00',
 'LINK 6005_B CLOSED AT TIME 38.00',
 'LINK 6005 OPEN AT TIME 43.75',
 '; Pipe 1951',
 'LINK 1951_A CLOSED AT TIME 39.00',
 'LINK 1951_B CLOSED AT TIME 39.00',
 'LINK 1951 OPEN AT TIME 46.25',
 '; Pipe 2409',
 'LINK 2409_A CLOSED AT TIME 42.50',
 'LINK 2409_B CLOSED AT TIME 42.50',
 'LINK 2409 OPEN AT TIME 45.75',
 '; Pipe 2821',
 'LINK 2821_A CLOSED AT TIME 44.50',
 'LINK 2821_B CLOSED AT TIME 44.50',
 'LINK 2821 OPEN AT TIME 47.75',
 '; Pipe 5567',
 'LINK 5567_A CLOSED AT TIME 46.50',
 'LINK 5567_B CLOSED AT TIME 46.50',
 'LINK 5567 OPEN AT TIME 49.25',
 '; Pipe 404',
 'LINK 404_A CLOSED AT TIME 46.50',
 'LINK 404_B CLOSED AT TIME 46.50',
 'LINK 404 OPEN AT TIME 49.25',
 '; Pipe 2307',
 'LINK 2307_A CLOSED AT TIME 48.00',
 'LINK 2307_B CLOSED AT TIME 48.00',
 'LINK 2307 OPEN AT TIME 51.25',
 '; Pipe 3414',
 'LINK 3414_A CLOSED AT TIME 49.50',
 'LINK 3414_B CLOSED AT TIME 49.50',
 'LINK 3414 OPEN AT TIME 56.75',
 '; Pipe 2535',
 'LINK 2535_A CLOSED AT TIME 50.00',
 'LINK 2535_B CLOSED AT TIME 50.00',
 'LINK 2535 OPEN AT TIME 53.50',
 '; Pipe 1568',
 'LINK 1568_A CLOSED AT TIME 51.75',
 'LINK 1568_B CLOSED AT TIME 51.75',
 'LINK 1568 OPEN AT TIME 54.50',
 '; Pipe 3074',
 'LINK 3074_A CLOSED AT TIME 53.75',
 'LINK 3074_B CLOSED AT TIME 53.75',
 'LINK 3074 OPEN AT TIME 56.50',
 '; Pipe 4882',
 'LINK 4882_A CLOSED AT TIME 55.00',
 'LINK 4882_B CLOSED AT TIME 55.00',
 'LINK 4882 OPEN AT TIME 57.75',
 '; Pipe 5775',
 'LINK 5775_A CLOSED AT TIME 57.00',
 'LINK 5775_B CLOSED AT TIME 57.00',
 'LINK 5775 OPEN AT TIME 60.50',
 '; Pipe 3875',
 'LINK 3875_A CLOSED AT TIME 57.00',
 'LINK 3875_B CLOSED AT TIME 57.00',
 'LINK 3875 OPEN AT TIME 61.25',
 '; Pipe 1865',
 'LINK 1865_A CLOSED AT TIME 58.50',
 'LINK 1865_B CLOSED AT TIME 58.50',
 'LINK 1865 OPEN AT TIME 61.25',
 '; Pipe 2094',
 'LINK 2094_A CLOSED AT TIME 61.25',
 'LINK 2094_B CLOSED AT TIME 61.25',
 'LINK 2094 OPEN AT TIME 66.00',
 '; Pipe 5042',
 'LINK 5042_A CLOSED AT TIME 61.75',
 'LINK 5042_B CLOSED AT TIME 61.75',
 'LINK 5042 OPEN AT TIME 64.50',
 '; Pipe 3859',
 'LINK 3859_A CLOSED AT TIME 61.75',
 'LINK 3859_B CLOSED AT TIME 61.75',
 'LINK 3859 OPEN AT TIME 64.50',
 '; Pipe 2543',
 'LINK 2543_A CLOSED AT TIME 65.00',
 'LINK 2543_B CLOSED AT TIME 65.00',
 'LINK 2543 OPEN AT TIME 68.50',
 '; Pipe 4622',
 'LINK 4622_A CLOSED AT TIME 65.00',
 'LINK 4622_B CLOSED AT TIME 65.00',
 'LINK 4622 OPEN AT TIME 67.75',
 '; Pipe 3125',
 'LINK 3125_A CLOSED AT TIME 66.25',
 'LINK 3125_B CLOSED AT TIME 66.25',
 'LINK 3125 OPEN AT TIME 69.75',
 '; Pipe 4177',
 'LINK 4177_A CLOSED AT TIME 68.25',
 'LINK 4177_B CLOSED AT TIME 68.25',
 'LINK 4177 OPEN AT TIME 71.00',
 '; Pipe 2816',
 'LINK 2816_A CLOSED AT TIME 68.75',
 'LINK 2816_B CLOSED AT TIME 68.75',
 'LINK 2816 OPEN AT TIME 71.50',
 '; Pipe 1402',
 'LINK 1402_A CLOSED AT TIME 70.00',
 'LINK 1402_B CLOSED AT TIME 70.00',
 'LINK 1402 OPEN AT TIME 72.75',
 '; Pipe 3104',
 'LINK 3104_A CLOSED AT TIME 71.25',
 'LINK 3104_B CLOSED AT TIME 71.25',
 'LINK 3104 OPEN AT TIME 74.75',
 '; Pipe 2016',
 'LINK 2016_A CLOSED AT TIME 71.75',
 'LINK 2016_B CLOSED AT TIME 71.75',
 'LINK 2016 OPEN AT TIME 74.50',
 '; Pipe 2440',
 'LINK 2440_A CLOSED AT TIME 73.00',
 'LINK 2440_B CLOSED AT TIME 73.00',
 'LINK 2440 OPEN AT TIME 75.75',
 '; Pipe 2053',
 'LINK 2053_A CLOSED AT TIME 74.75',
 'LINK 2053_B CLOSED AT TIME 74.75',
 'LINK 2053 OPEN AT TIME 78.00',
 '; Pipe 4538',
 'LINK 4538_A CLOSED AT TIME 75.25',
 'LINK 4538_B CLOSED AT TIME 75.25',
 'LINK 4538 OPEN AT TIME 78.00',
 '; Pipe 4035',
 'LINK 4035_A CLOSED AT TIME 76.00',
 'LINK 4035_B CLOSED AT TIME 76.00',
 'LINK 4035 OPEN AT TIME 80.25',
 '; Pipe 538',
 'LINK 538_A CLOSED AT TIME 78.25',
 'LINK 538_B CLOSED AT TIME 78.25',
 'LINK 538 OPEN AT TIME 81.00',
 '; Pipe 5871',
 'LINK 5871_A CLOSED AT TIME 78.25',
 'LINK 5871_B CLOSED AT TIME 78.25',
 'LINK 5871 OPEN AT TIME 84.25',
 '; Pipe 190',
 'LINK 190_A CLOSED AT TIME 80.50',
 'LINK 190_B CLOSED AT TIME 80.50',
 'LINK 190 OPEN AT TIME 83.25',
 '; Pipe 2216',
 'LINK 2216_A CLOSED AT TIME 81.25',
 'LINK 2216_B CLOSED AT TIME 81.25',
 'LINK 2216 OPEN AT TIME 84.50',
 '; Pipe 2622',
 'LINK 2622_A CLOSED AT TIME 83.50',
 'LINK 2622_B CLOSED AT TIME 83.50',
 'LINK 2622 OPEN AT TIME 86.25',
 '; Pipe 3760',
 'LINK 3760_A CLOSED AT TIME 84.75',
 'LINK 3760_B CLOSED AT TIME 84.75',
 'LINK 3760 OPEN AT TIME 88.00',
 '; Pipe 4942',
 'LINK 4942_A CLOSED AT TIME 85.00',
 'LINK 4942_B CLOSED AT TIME 85.00',
 'LINK 4942 OPEN AT TIME 87.75',
 '; Pipe 1657',
 'LINK 1657_A CLOSED AT TIME 86.50',
 'LINK 1657_B CLOSED AT TIME 86.50',
 'LINK 1657 OPEN AT TIME 89.25',
 '; Pipe 762',
 'LINK 762_A CLOSED AT TIME 88.25',
 'LINK 762_B CLOSED AT TIME 88.25',
 'LINK 762 OPEN AT TIME 91.50',
 '; Pipe 3679',
 'LINK 3679_A CLOSED AT TIME 88.25',
 'LINK 3679_B CLOSED AT TIME 88.25',
 'LINK 3679 OPEN AT TIME 92.50',
 '; Pipe 4246',
 'LINK 4246_A CLOSED AT TIME 89.50',
 'LINK 4246_B CLOSED AT TIME 89.50',
 'LINK 4246 OPEN AT TIME 93.75',
 '; Pipe 2141',
 'LINK 2141_A CLOSED AT TIME 91.75',
 'LINK 2141_B CLOSED AT TIME 91.75',
 'LINK 2141 OPEN AT TIME 96.50',
 '; Pipe 2730',
 'LINK 2730_A CLOSED AT TIME 92.75',
 'LINK 2730_B CLOSED AT TIME 92.75',
 'LINK 2730 OPEN AT TIME 95.50',
 '; Pipe 3449',
 'LINK 3449_A CLOSED AT TIME 94.00',
 'LINK 3449_B CLOSED AT TIME 94.00',
 'LINK 3449 OPEN AT TIME 98.75',
 '; Pipe 501',
 'LINK 501_A CLOSED AT TIME 95.75',
 'LINK 501_B CLOSED AT TIME 95.75',
 'LINK 501 OPEN AT TIME 98.50',
 '; Pipe 3564',
 'LINK 3564_A CLOSED AT TIME 96.75',
 'LINK 3564_B CLOSED AT TIME 96.75',
 'LINK 3564 OPEN AT TIME 101.25',
 '; Pipe 4022',
 'LINK 4022_A CLOSED AT TIME 98.75',
 'LINK 4022_B CLOSED AT TIME 98.75',
 'LINK 4022 OPEN AT TIME 101.50',
 '; Pipe 2114',
 'LINK 2114_A CLOSED AT TIME 99.00',
 'LINK 2114_B CLOSED AT TIME 99.00',
 'LINK 2114 OPEN AT TIME 101.75',
 '; Pipe 1477',
 'LINK 1477_A CLOSED AT TIME 101.50',
 'LINK 1477_B CLOSED AT TIME 101.50',
 'LINK 1477 OPEN AT TIME 104.25',
 '; Pipe 4101',
 'LINK 4101_A CLOSED AT TIME 101.75',
 'LINK 4101_B CLOSED AT TIME 101.75',
 'LINK 4101 OPEN AT TIME 104.50',
 '; Pipe 1724',
 'LINK 1724_A CLOSED AT TIME 102.00',
 'LINK 1724_B CLOSED AT TIME 102.00',
 'LINK 1724 OPEN AT TIME 104.75',
 '; Pipe 5677',
 'LINK 5677_A CLOSED AT TIME 104.75',
 'LINK 5677_B CLOSED AT TIME 104.75',
 'LINK 5677 OPEN AT TIME 107.50',
 '; Pipe 4409',
 'LINK 4409_A CLOSED AT TIME 105.00',
 'LINK 4409_B CLOSED AT TIME 105.00',
 'LINK 4409 OPEN AT TIME 111.75',
 '; Pipe 5488',
 'LINK 5488_A CLOSED AT TIME 105.50',
 'LINK 5488_B CLOSED AT TIME 105.50',
 'LINK 5488 OPEN AT TIME 108.25',
 '; Pipe 6023',
 'LINK 6023_A CLOSED AT TIME 107.75',
 'LINK 6023_B CLOSED AT TIME 107.75',
 'LINK 6023 OPEN AT TIME 112.25',
 '; Pipe 854',
 'LINK 854_A CLOSED AT TIME 108.75',
 'LINK 854_B CLOSED AT TIME 108.75',
 'LINK 854 OPEN AT TIME 111.50',
 '; Pipe 5778',
 'LINK 5778_A CLOSED AT TIME 112.25',
 'LINK 5778_B CLOSED AT TIME 112.25',
 'LINK 5778 OPEN AT TIME 115.00',
 '; Pipe 1464',
 'LINK 1464_A CLOSED AT TIME 112.25',
 'LINK 1464_B CLOSED AT TIME 112.25',
 'LINK 1464 OPEN AT TIME 115.00',
 '; Pipe 4062',
 'LINK 4062_A CLOSED AT TIME 113.00',
 'LINK 4062_B CLOSED AT TIME 113.00',
 'LINK 4062 OPEN AT TIME 116.25',
 '; Pipe 5140',
 'LINK 5140_A CLOSED AT TIME 115.75',
 'LINK 5140_B CLOSED AT TIME 115.75',
 'LINK 5140 OPEN AT TIME 118.50',
 '; Pipe 1105',
 'LINK 1105_A CLOSED AT TIME 115.75',
 'LINK 1105_B CLOSED AT TIME 115.75',
 'LINK 1105 OPEN AT TIME 119.00',
 '; Pipe 4880',
 'LINK 4880_A CLOSED AT TIME 116.75',
 'LINK 4880_B CLOSED AT TIME 116.75',
 'LINK 4880 OPEN AT TIME 119.50',
 '; Pipe 892',
 'LINK 892_A CLOSED AT TIME 119.00',
 'LINK 892_B CLOSED AT TIME 119.00',
 'LINK 892 OPEN AT TIME 121.75',
 '; Pipe 4915',
 'LINK 4915_A CLOSED AT TIME 119.50',
 'LINK 4915_B CLOSED AT TIME 119.50',
 'LINK 4915 OPEN AT TIME 123.00',
 '; Pipe 4507',
 'LINK 4507_A CLOSED AT TIME 119.75',
 'LINK 4507_B CLOSED AT TIME 119.75',
 'LINK 4507 OPEN AT TIME 122.50',
 '; Pipe 4764',
 'LINK 4764_A CLOSED AT TIME 122.25',
 'LINK 4764_B CLOSED AT TIME 122.25',
 'LINK 4764 OPEN AT TIME 125.00',
 '; Pipe 3726',
 'LINK 3726_A CLOSED AT TIME 123.00',
 'LINK 3726_B CLOSED AT TIME 123.00',
 'LINK 3726 OPEN AT TIME 125.75',
 '; Pipe 3122',
 'LINK 3122_A CLOSED AT TIME 123.50',
 'LINK 3122_B CLOSED AT TIME 123.50',
 'LINK 3122 OPEN AT TIME 126.25',
 '; Pipe 4594',
 'LINK 4594_A CLOSED AT TIME 125.25',
 'LINK 4594_B CLOSED AT TIME 125.25',
 'LINK 4594 OPEN AT TIME 128.00',
 '; Pipe 4788',
 'LINK 4788_A CLOSED AT TIME 126.25',
 'LINK 4788_B CLOSED AT TIME 126.25',
 'LINK 4788 OPEN AT TIME 130.50',
 '; Pipe 4038',
 'LINK 4038_A CLOSED AT TIME 126.50',
 'LINK 4038_B CLOSED AT TIME 126.50',
 'LINK 4038 OPEN AT TIME 130.75',
 '; Pipe 2983',
 'LINK 2983_A CLOSED AT TIME 128.50',
 'LINK 2983_B CLOSED AT TIME 128.50',
 'LINK 2983 OPEN AT TIME 131.75',
 '; Pipe 1807',
 'LINK 1807_A CLOSED AT TIME 131.00',
 'LINK 1807_B CLOSED AT TIME 131.00',
 'LINK 1807 OPEN AT TIME 133.75',
 '; Pipe 1989',
 'LINK 1989_A CLOSED AT TIME 131.00',
 'LINK 1989_B CLOSED AT TIME 131.00',
 'LINK 1989 OPEN AT TIME 133.75',
 '; Pipe 1373',
 'LINK 1373_A CLOSED AT TIME 132.25',
 'LINK 1373_B CLOSED AT TIME 132.25',
 'LINK 1373 OPEN AT TIME 135.00',
 '; Pipe 4083',
 'LINK 4083_A CLOSED AT TIME 134.00',
 'LINK 4083_B CLOSED AT TIME 134.00',
 'LINK 4083 OPEN AT TIME 137.25',
 '; Pipe 6041',
 'LINK 6041_A CLOSED AT TIME 134.50',
 'LINK 6041_B CLOSED AT TIME 134.50',
 'LINK 6041 OPEN AT TIME 137.25',
 '; Pipe 2430',
 'LINK 2430_A CLOSED AT TIME 135.50',
 'LINK 2430_B CLOSED AT TIME 135.50',
 'LINK 2430 OPEN AT TIME 138.25',
 '; Pipe 5691',
 'LINK 5691_A CLOSED AT TIME 137.75',
 'LINK 5691_B CLOSED AT TIME 137.75',
 'LINK 5691 OPEN AT TIME 141.00',
 '; Pipe 4132',
 'LINK 4132_A CLOSED AT TIME 138.00',
 'LINK 4132_B CLOSED AT TIME 138.00',
 'LINK 4132 OPEN AT TIME 141.50',
 '; Pipe 5105',
 'LINK 5105_A CLOSED AT TIME 139.00',
 'LINK 5105_B CLOSED AT TIME 139.00',
 'LINK 5105 OPEN AT TIME 141.75']

In [10]:
# Apply function to generate INP with controls
controls_inp = MOO_functions.write_inp_controls(
    input_inp=input_inp,
    output_inp=output_inp,
    schedule=schedule,
    new_controls=new_controls
)

print(f"Created: {controls_inp}")

Created: BBM-EPS_DS2_restoration.inp